- src/glb-director/main.c
Hate to be _that_ guy, but found this typo while looking around the code.
> Fix handler typo

- src/glb-redirect/ipt_GLBREDIRECT.c
There are two API changes between 4.9 and 4.14 which need to be addressed.
* struct xt_action_param does not carry struct net anymore. It needs to be
accessed via xt_net().
Upstream commit 613dbd95723aee7abd16860745691b6c7bda20dc
* The hash table lookups have gained an additional sdif parameter, which is
used for enslaved devices.
Upstream commit 3fa6f616a7a4d0bdf4d877d530456d8a5c3b109b
> Support building on latest LTS kernel (4.14)

- src/glb-redirect/libxt_GLBREDIRECT.c
This workaround was added due to build errors on Ubuntu Precise many years ago, but since Precise is EOL and glb-director doesn't intend to support it, it makes sense to remove it.
Fixes https://github.com/github/glb-director/issues/32
> Remove workaround for Ubuntu Precise kernel builds.

- script/Dockerfile.stretch
- src/glb-healthcheck/script/cibuild
Fixes https://github.com/github/glb-director/issues/33, which reported build errors due to missing `vendor`ed packages. This PR adds `glide`, and then installs the packages we have configured, during `cibuild`.
> glb-healthcheck: Install glide and run `glide install` before building.

- .gitignore
- src/glb-director/cli/Makefile
- src/glb-director/cli/pcap_mode.c
- src/glb-director/cli/stub_server.c
- src/glb-director/glb_encap.c
- src/glb-director/glb_encap.h
- src/glb-director/glb_encap_dpdk.c
- src/glb-director/glb_encap_pcap.c
- src/glb-director/glb_encap_pcap.h
This PR refactors the parsing of packets and subsequent retrieval of fields for flow hashing to be more isolated and resilient, in preparation for allowing customisation of the fields used in flow hashing. More specifically:
* Parsing is changed from assuming a non-segmented packet, to `rte_pktmbuf_read` which supports linearising packet data if required.
* The `linearisation_space` used here automates / hides away the implementation detail of requiring space for `rte_pktmbuf_read` to linearise segmented packets.
* Field extraction and hashing are split apart, in preparation for the fields used in hashing being varied based on configuration.
* The change from primary/secondary to route_context with next hops also prepares for allowing a variable sized list of next hops. The implementation …
> Refactor packet parsing and flow hash calculation.

- src/glb-redirect/ipt_GLBREDIRECT.c
Silence the iptables validation callback by default. This otherwise
creates a lot of noise if people test their rules via iptables-restore
before committing them.
> glb-redirect: only print "Validating ..." message in debug mode

- src/glb-redirect/ipt_GLBREDIRECT.c
It took me a while to figure out that the rule redirecting to
glb-redirect has to match on the UDP protocol. Print a message
to dmesg in case verification fails to make this clearer.
> Write to dmesg if glb-redirect verification fails

- src/glb-redirect/ipt_GLBREDIRECT.c
Commit "netfilter: conntrack: remove l3proto abstraction" (a0ae2562c6c4b272)
breaks the build, since it removes nf_ct_l3proto_try_module_get and
nf_ct_l3proto_module_put. Use the usual preprocessor magic to fix this.
> Fix building on v4.19

- requirements.txt
The latest Scapy upgraded quietly and broke tests because it can't detect local routes anymore, so the tests started using broadcast MAC addresses.
> Pin versions and downgrade Scapy.

- Vagrantfile
- script/helpers/test-snoop.py
- script/helpers/test-snoop.service
- src/glb-redirect/ipt_GLBREDIRECT.c
- src/glb-redirect/tests/glb_test_remote_snoop.py
- src/glb-redirect/tests/glb_test_utils.py
- src/glb-redirect/tests/test_glb_redirect_v4_on_v4.py
- src/glb-redirect/tests/test_glb_redirect_v6_on_v4.py
Path MTU discovery requires that Packet Too Big messages are delivered
to the machine "responsible" for a given flow. Modify glb-redirect
so that it reconstructs the original flow tuple from the ICMP message,
and make it pass such messages along the chain.
Add a helper function which creates a fake TCP header from
the ICMP payload, adjusting for the direction of the flow.
This is then used to check whether a connection is known locally.
Fixes #47
> glb-redirect: support path MTU discovery

- src/glb-redirect/Makefile
Since we only use glb-redirect, it's useful for us to be able to
make mkdeb just for glb-redirect. Fix up the Makefile to make this
possible.
> glb-redirect: allow standalone mkdeb invocation

- src/glb-redirect/dkms.conf
Picks up a few good bug fixes that landed in `master` but haven't seen a release yet.
> Update package version for glb-redirect to 1.0.5.

- src/glb-redirect/ipt_GLBREDIRECT.c
When a SYN packet is received, Linux creates a so called request socket.
This is smaller than a full socket, and helps conserve resources. Request
sockets (aka reqsk) always have sk_state equal to TCP_NEW_SYN_RECV, and
are part of the inet hash tables. This means they are returned by a call
to inet_lookup_established and friends.
This is true as of v4.4, and was introduced by commit https://github.com/torvalds/linux/commit/079096f103faca2dd87342cca6f23d4b34da8871
Fixes #50
> Remove conntrack lookups

- src/glb-redirect/ipt_GLBREDIRECT.c
Linux commit 895b5c9f206eb ("netfilter: drop bridge nf reset from nf_reset ")
renamed nf_reset to nf_reset_ct. Use the new function on >= 5.4 kernels.
Fixes #82
> glb-redirect: fix compilation on 5.4-rc2

- src/glb-redirect/ipt_GLBREDIRECT.c
Strictly speaking, https://github.com/torvalds/linux/commit/8203e2d844d34 is included since Linux 4.20 and the condition may need to be more relaxed. We only run LTS versions, so 4.19 and 5.4 are the only two kernels I tested on.
Eric Dumazet blessed this change:
And we can finally see Linux 5.4 not aiming to send the next packet in 50 years:
* https://lists.openwall.net/netdev/2019/10/29/177
Before:
```
qdisc fq 1: dev ext0 root refcnt 65 limit 10000p flow_limit 100p buckets 1024 orphan_mask 1023 quantum 3228 initial_quantum 16140 low_rate_threshold 550Kbit refill_delay 40.0ms
Sent 4872143400 bytes 8448638 pkt (dropped 201276670, overlimits 0 requeues 103)
backlog 779376b 10000p requeues 103
2806 flows (2688 inactive, 118 throttled), next packet delay 1572240566653952889 ns
354201 gc, 0 …
```
> Clear our skb timestamp to unbreak fq

- .github/workflows/ci.yml
This at least validates builds in a consistent way using CI. Ideally we'd get the full test suite running too, but I need to look more into what's supported there with actions since it uses Vagrant right now.
> Add simple actions CI job to run cibuild-create-packages

- src/glb-director/cli/Makefile
- src/glb-director/cli/stub_server.c
- src/glb-director/shared_opt.c
- src/glb-director/shared_opt.h
- src/glb-director/siphash24.c
- src/glb-director/util.h
- src/glb-redirect/Makefile
This commit brings in changes to allow building glb-director, glb-healthcheck,
glb-redirect as individual components on a Linux device where all the
underlying dependencies are present.
Without these changes, the foregoing components could not individually be built
(without the use of Docker) due to mismatches between expectations of different
respective versions of gcc and linker.
> Building glb components natively on Linux (without the cibuild):

- Vagrantfile
- script/Dockerfile.stretch
- src/glb-director/Makefile
- src/glb-director/main.c
- src/glb-director/packaging/glb-director.service
Currently when starting glb-director using systemd, there's no way to use systemd dependencies to trigger subsequent services once glb-director is actually started.
By adding this call to [sd_notify](https://www.freedesktop.org/software/systemd/man/sd_notify.html#), and setting the service to `Type=notify`, systemd will understand that the service isn't fully started until it has loaded the initial forwarding table and all workers are launched and ready to process packets.
> glb-director: Enable systemd ready notification.

- script/Dockerfile.stretch
The [debian linux-image-amd64 metapackage](https://packages.debian.org/stretch-backports/linux-image-amd64) in `stretch-backports` has recently been broken since the `linux-image-4.19.0-0.bpo.8-amd64` package doesn't exist, only `linux-image-4.19.0-0.bpo.8-amd64-unsigned`. Let's use that for now to un-break package building until the repository is fixed.
> Fix broken Debian Stretch kernel dependency in package building.

- docs/setup/forwarding-table-config.md
- docs/setup/glb-healthcheck-configuration.md
- src/glb-healthcheck/GLBTable.go
- src/glb-healthcheck/HealthCheckManager.go
- src/glb-healthcheck/HealthCheckerAppContext.go
- src/glb-healthcheck/main.go
Configured values apply for all backends across all tables.
Config stanza: in /etc/glb/forwarding_table.src.json (same level as tables[]):
eg.
{
"healthcheck_global_cfg":
{
"interval_ms": 4000,
"timeout_ms": 2000,
"trigger": 4
}
}
Interval & timeout values are in milli-seconds.
Timeout value should be less than the interval.
Trigger is an absolute number.
> GLB health-checks: parameter configurability: 

- src/glb-healthcheck/main.go
This PR fixes a regression introduced in https://github.com/github/glb-director/commit/43a9a238f0ed88980e949e4e53905fea46b82e26 which separated `SyncBackendsToCheckManager` out of the load function so that at initialisation time some additional work could be done, but missed the other call site during reloads. This adds back the sync in that location.
> glb-healthcheck: Add missing sync call on reload.

- src/glb-director-xdp/packaging/version.sh
- src/glb-director-xdp/packaging/xdp-root-shim@.service
Bringing up XDP on a new interface for the first time causes the interface to temporarily go down and back up. By ensuring that the XDP shim is brought online prior to `network-online.target`, we ensure that programs that rely on stable network interfaces are not started until this process has completed.
> xdp-root-shim: Start between network.target and network-online.target.

- src/glb-redirect/dkms.conf
This includes the patch from https://github.com/github/glb-director/pull/118 which fixes compilation on newer kernels.
> Update package version for glb-redirect to 1.0.6.

- script/Dockerfile.stretch
fpm 1.12 generates deb packages with a failing postinst script, as described in https://github.com/jordansissel/fpm/issues/1749. 
When I run `scripts/cibuild`, the setup fails for `glb-healthcheck` and `glb-director` packages.
After I pinned the fpm version like this PR does, `scripts/cibuild` completed successfully.
> Pin fpm to a working version

- requirements.txt
Scapy broke back in #53 but the current version is 2.4.5 - and the issue was fixed in 2.4.3. To work this out I temporarily modified script/test to install a specific version of scapy before running the tests - and could see pretty quickly when it was fixed.
```
vagrant@director-test:/vagrant/src/glb-redirect$ sudo script/test 2.4.0 2>&1 | grep broadcast
vagrant@director-test:/vagrant/src/glb-redirect$ sudo script/test 2.4.1 2>&1 | grep broadcast
scapy.runtime: WARNING: Mac address to reach destination not found. Using broadcast.
scapy.runtime: WARNING: Mac address to reach destination not found. Using broadcast.
vagrant@director-test:/vagrant/src/glb-redirect$ sudo script/test 2.4.2 2>&1 | grep broadcast
scapy.runtime: WARNING: Mac address to reach destination not found. Using broadcast. …
```
> Update python dependencies to newest possible versions.

- requirements.txt
https://github.com/github/glb-director/pull/142 failed to set the correct version for scapy - this fixes that.
> Actually pin scapy to 2.4.5

- .github/workflows/ci.yml
- src/glb-redirect/Makefile
- src/glb-redirect/ipt_GLBREDIRECT.c
In kernels >= 5.6 `file_operations` was deprecated and replaced with `proc_ops`. This adds support for this.
> This adds compatibility for kernel >= 5.6

- src/glb-director-xdp/script/create-packages
Bumped version of `libbpf` to use the current [libbpf0](https://packages.ubuntu.com/source/focal-updates/libbpf)
> Update version of package dependencies for xdp
